USE [master]
GO

/****** Object:  Database [AsyncTest]    Script Date: 04/21/2014 17:24:32 ******/
CREATE DATABASE [AsyncTest] ON  PRIMARY 
( NAME = N'AsyncTest', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\AsyncTest.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AsyncTest_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\AsyncTest_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AsyncTest] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AsyncTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AsyncTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AsyncTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AsyncTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AsyncTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AsyncTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [AsyncTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AsyncTest] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AsyncTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AsyncTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AsyncTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AsyncTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AsyncTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AsyncTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AsyncTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AsyncTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AsyncTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AsyncTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AsyncTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AsyncTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AsyncTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AsyncTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AsyncTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AsyncTest] SET  READ_WRITE 
GO

ALTER DATABASE [AsyncTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AsyncTest] SET  MULTI_USER 
GO

ALTER DATABASE [AsyncTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AsyncTest] SET DB_CHAINING OFF 
GO


